### ISSUE TITLE
cannot find name of tty

### ISSUE THREAD

**Issue by jasonehines** [tbodt/ish#287]
I created an new user and added them to the sudo group and allowed them in /etc/sudoers. But when I try to run sudo as that user, I get the usual first run sudo message and `sudo: no tty present and no askpass program specified`

Am I doing something wrong or is this not implemented yet?

I also checked the sudo config and requiretty is not specified.

**Comment by tbodt** [comment]
This is because when you run programs normally ttyname fails.

**Comment by jasonehines** [comment]
okay. I did a little googling and didn't find any obvious solutions. Since this is still open, does that mean it's an issue in ish?

**Comment by tbodt** [comment]
Yep, it'll get fixed eventually.

This might actually work if you do it over an ssh connection.

**Comment by jasonehines** [comment]
I just tried it over ssh and it gave me the same message.

**Comment by tbodt** [comment]
darn. guess I'm wrong then

**Comment by tbodt** [comment]
This should be fixed now

**Comment by philips** [comment]
This sudo giving no tty present and no askpass program specified this is happening to me now. Happy to try debugging steps.

**Comment by Pheoxy** [comment]
I’m getting the same response on adding a user and after:
`su user`
`sudo app update`

`sudo: no tty present and no askpass program specified`

**Comment by kkk669** [comment]
Doing sudo via SSH is ok, but the following issue still occurs as @Pheoxy reported.

```console
# su user
$ sudo ls
sudo: no tty present and no askpass program specified
```

I'm using iSH 1.0 build 62 (TestFlight) on PadOS 13.2.

**Comment by tbodt** [comment]
Probably something to do with the interaction with multiwindow.
